#!/bin/bash

PROJECT_ROOT=../../../

mvn dependency:build-classpath -f=$PROJECT_ROOT/pom.xml -Dmdep.outputFile=target/sh/cp.txt
CP=`cat $PROJECT_ROOT/target/sh/cp.txt`
CP=$CP:$PROJECT_ROOT/target/classes:$PROJECT_ROOT/target/test-classes
CP=$CP:$PROJECT_ROOT/src/main/resources/
#java -javaagent:/src/jrebel/jrebel.jar -cp $CP org.apache.drill.exec.server.Drillbit
java -cp $CP org.apache.drill.exec.server.Drillbit -c $PROJECT_ROOT/src/test/resources/drill-module.conf

